"""
Alembic migration tests.

init_db() runs `alembic upgrade head` on every backend start, so a broken
migration chain takes the whole app down at boot rather than failing some
isolated request. These cover the two paths that actually happen in deployment:
a brand-new database, and an existing pre-Alembic one being adopted.
"""

import importlib
import os
import sys

import pytest
from alembic import command
from alembic.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import inspect, text

# Every table the baseline is expected to build.
EXPECTED_TABLES = {
    "locations", "users", "signatures", "prescriptions", "audit_log",
    "patients", "xrays", "detections", "referral_slips",
}


@pytest.fixture()
def db_module(tmp_path, monkeypatch):
    """A freshly imported db.py bound to a throwaway database.

    alembic/env.py imports db itself to read the URL, so monkeypatching an
    already-imported module is not enough -- env.py would still resolve the real
    engine and migrate the developer's own smileai.db. Setting DATABASE_URL and
    re-importing is what the app actually does at boot, and it is the only way
    the migration and the assertions end up on the same database.
    """
    path = str(tmp_path / "migrate.db").replace("\\", "/")
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{path}")

    for name in ("main", "db", "auth"):
        sys.modules.pop(name, None)

    module = importlib.import_module("db")
    yield module

    module.engine.dispose()
    # Leave no half-configured db module behind for the next test.
    for name in ("main", "db", "auth"):
        sys.modules.pop(name, None)


def _revision(engine):
    with engine.connect() as conn:
        return MigrationContext.configure(conn).get_current_revision()


def _head(db_module):
    return ScriptDirectory.from_config(
        db_module._alembic_config()).get_current_head()


def test_fresh_database_upgrades_to_head(db_module):
    """A colleague's first run builds the whole schema from migrations alone."""
    db_module.init_db()

    tables = set(inspect(db_module.engine).get_table_names())
    assert EXPECTED_TABLES <= tables, f"missing: {EXPECTED_TABLES - tables}"
    assert _revision(db_module.engine) == _head(db_module)


def test_init_db_is_idempotent(db_module):
    """Every restart calls init_db(); the second one must be a no-op."""
    db_module.init_db()
    first = _revision(db_module.engine)

    db_module.init_db()

    assert _revision(db_module.engine) == first


def test_no_model_schema_drift(db_module):
    """The models and the migrations must not disagree.

    Catches the common mistake of editing db.py without generating a revision.
    """
    db_module.init_db()

    # Raises AutogenerateDiffsDetected if anything is undeclared.
    command.check(db_module._alembic_config())


def test_legacy_database_is_stamped_not_rebuilt(db_module):
    """A pre-Alembic database is adopted without losing its rows.

    Simulates the real AWS/developer case: tables built by the old create_all()
    path, no alembic_version, and columns that arrived via ALTER TABLE without
    their indexes or foreign keys.
    """
    # Build the schema the old way, then strip Alembic's bookkeeping so it looks
    # exactly like a database created before migrations existed.
    db_module.Base.metadata.create_all(bind=db_module.engine)
    with db_module.engine.begin() as conn:
        conn.execute(text("DROP TABLE IF EXISTS alembic_version"))
        conn.execute(text(
            "INSERT INTO patients (id, mrn, name) VALUES (1, 'MRN-1', 'Test')"))

    assert _revision(db_module.engine) is None, "precondition: not under Alembic"

    db_module.init_db()

    assert _revision(db_module.engine) == _head(db_module)
    with db_module.engine.connect() as conn:
        rows = conn.execute(text("SELECT mrn FROM patients")).fetchall()
    assert [r[0] for r in rows] == ["MRN-1"], "existing data must survive"


def test_legacy_database_missing_newer_columns_and_tables(db_module):
    """A legacy database that predates whole features must still upgrade.

    How far the old ALTER TABLE path got varies by deployment. Production was
    last migrated before reusable e-signatures and the review lock existed, so
    it had no `signatures` table and no xrays.claimed_* columns -- while a
    developer's database had both. The first deploy of revision 1d1fe49baabb
    crash-looped on `CREATE INDEX ... (claimed_by_id)` because the migration
    assumed the column was merely missing its index.

    Stamping skips the baseline, so a table the legacy schema never had would
    otherwise never be created by any revision.
    """
    db_module.Base.metadata.create_all(bind=db_module.engine)
    with db_module.engine.begin() as conn:
        conn.execute(text("DROP TABLE IF EXISTS alembic_version"))
        conn.execute(text("DROP TABLE IF EXISTS signatures"))
        # SQLite refuses to DROP a column named in a foreign key, so rebuild
        # xrays without the review-lock columns rather than altering it.
        conn.execute(text("DROP TABLE xrays"))
        conn.execute(text(
            "CREATE TABLE xrays ("
            " id INTEGER NOT NULL PRIMARY KEY,"
            " patient_id INTEGER REFERENCES patients(id),"
            " original_filename VARCHAR(255) NOT NULL,"
            " file_path VARCHAR(500) NOT NULL,"
            " status VARCHAR(20) NOT NULL,"
            " image_width INTEGER, image_height INTEGER,"
            " appointment_date DATETIME, uploaded_at DATETIME,"
            " processed_at DATETIME, error_message TEXT,"
            # assigned_* exist (the old path added them); claimed_* do not.
            " assigned_to_id INTEGER, assigned_at DATETIME,"
            " assigned_by_id INTEGER)"))
        conn.execute(text(
            "INSERT INTO patients (id, mrn, name) VALUES (1, 'MRN-1', 'Test')"))

    db_module.init_db()

    insp = inspect(db_module.engine)
    assert "signatures" in insp.get_table_names()
    xray_columns = {c["name"] for c in insp.get_columns("xrays")}
    assert {"claimed_by_id", "claimed_at"} <= xray_columns
    assert _revision(db_module.engine) == _head(db_module)

    with db_module.engine.connect() as conn:
        rows = conn.execute(text("SELECT mrn FROM patients")).fetchall()
    assert [r[0] for r in rows] == ["MRN-1"]


def test_already_stamped_database_still_gets_signatures(db_module):
    """A database stamped by an earlier deploy must still gain `signatures`.

    _stamp_legacy_database() creates tables the legacy schema never had, but it
    only runs the first time a database is adopted. Production had already been
    stamped by a previous deploy, so on the next boot that path short-circuited
    and `signatures` stayed missing -- while /api/health reported OK, because
    nothing touches the table at startup. Revision 4b8d2c5e7a91 repairs it from
    inside the migration chain, which applies regardless of adoption history.
    """
    db_module.init_db()
    with db_module.engine.begin() as conn:
        conn.execute(text("DROP TABLE IF EXISTS signatures"))
        # Rewind only the signatures revision; the rest of the chain stays.
        conn.execute(text(
            "UPDATE alembic_version SET version_num = '3c7e1a2b9f04'"))

    assert "signatures" not in inspect(db_module.engine).get_table_names()

    db_module.init_db()

    assert "signatures" in inspect(db_module.engine).get_table_names()
    assert _revision(db_module.engine) == _head(db_module)


def test_legacy_upgrade_adds_missing_indexes(db_module):
    """Revision 1d1fe49baabb backfills what ALTER TABLE ADD COLUMN could not."""
    db_module.Base.metadata.create_all(bind=db_module.engine)
    with db_module.engine.begin() as conn:
        conn.execute(text("DROP TABLE IF EXISTS alembic_version"))

    db_module.init_db()

    indexes = {i["name"] for i in inspect(db_module.engine).get_indexes("xrays")}
    assert "ix_xrays_assigned_to_id" in indexes
    assert "ix_xrays_claimed_by_id" in indexes


def test_downgrade_and_reupgrade_round_trips(db_module):
    """A bad deploy must be reversible."""
    db_module.init_db()
    cfg = db_module._alembic_config()

    command.downgrade(cfg, "-1")
    assert _revision(db_module.engine) != _head(db_module)

    command.upgrade(cfg, "head")
    assert _revision(db_module.engine) == _head(db_module)


def test_offline_sql_generation_works_for_postgres(db_module, tmp_path,
                                                   monkeypatch):
    """`alembic upgrade head --sql` must render the whole chain for RDS.

    This is how a schema change gets reviewed before it touches production. The
    guards in the revisions call inspect(), which has no database to look at in
    offline mode -- so every one of them needs an is_offline_mode() branch, and
    forgetting it breaks the review path without breaking any live upgrade.

    Postgres is the deployed engine, so render against that dialect, not SQLite.
    """
    monkeypatch.setenv(
        "DATABASE_URL", "postgresql+psycopg2://u:p@localhost:5432/smileai")

    for name in ("main", "db", "auth"):
        sys.modules.pop(name, None)
    pg_db = importlib.import_module("db")

    out = tmp_path / "upgrade.sql"
    cfg = pg_db._alembic_config()
    with open(out, "w", encoding="utf-8") as fh:
        monkeypatch.setattr(sys, "stdout", fh)
        command.upgrade(cfg, "head", sql=True)

    sql = out.read_text(encoding="utf-8")
    assert "CREATE TABLE users" in sql
    # The named constraints from 1d1fe49baabb: an unnamed one fails on Postgres.
    assert "fk_xrays_claimed_by_id_users" in sql
    assert "ADD COLUMN findings_json" in sql


def test_migration_files_are_packaged(db_module):
    """alembic.ini and the versions directory must ship with the app.

    The Dockerfile copies files by name, so a new migration that is not picked
    up would only surface as a container that will not boot.
    """
    assert os.path.exists(db_module.ALEMBIC_INI)
    versions = os.path.join(db_module.BASE_DIR, "alembic", "versions")
    scripts = [f for f in os.listdir(versions) if f.endswith(".py")]
    assert scripts, "no migration scripts found"
