"""baseline schema

The full schema as it stood when Alembic was introduced: every table that the
old create_all() + _add_missing_columns() path used to build.

An EXISTING database (a developer's smileai.db, or RDS) already has all of this,
so it must be stamped rather than upgraded:

    alembic stamp 2a9de32687b8

Running `upgrade` against such a database would fail on the first CREATE TABLE.
Fresh databases have nothing to stamp and should just run `alembic upgrade head`.

Revision ID: 2a9de32687b8
Revises:
Create Date: 2026-08-09 17:06:55.876468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9de32687b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mrn', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_mrn'), ['mrn'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('primary_location_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['primary_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_id'), ['id'], unique=False)

    op.create_table('signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signatures_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signatures_user_id'), ['user_id'], unique=False)

    op.create_table('xrays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('claimed_by_id', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claimed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('xrays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xrays_appointment_date'), ['appointment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_xrays_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xrays_claimed_by_id'), ['claimed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xrays_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xrays_status'), ['status'], unique=False)

    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xray_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=10), server_default='detect', nullable=False),
    sa.Column('disease', sa.String(length=50), nullable=True),
    sa.Column('fdi_number', sa.String(length=10), nullable=True),
    sa.Column('universal_number', sa.String(length=10), nullable=True),
    sa.Column('quadrant', sa.String(length=30), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=False),
    sa.Column('polygon_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('impaction_type', sa.String(length=50), nullable=True),
    sa.Column('needs_extraction', sa.Boolean(), nullable=False),
    sa.Column('marked_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['xray_id'], ['xrays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_xray_id'), ['xray_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xray_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('clinician_name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('location_name_snapshot', sa.String(length=120), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('prescription_text', sa.Text(), nullable=True),
    sa.Column('dictation_text', sa.Text(), nullable=True),
    sa.Column('signature_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('amends_id', sa.Integer(), nullable=True),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['amends_id'], ['prescriptions.id'], ),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['xray_id'], ['xrays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_clinician_id'), ['clinician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_xray_id'), ['xray_id'], unique=False)

    op.create_table('referral_slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xray_id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=True),
    sa.Column('prescription_text', sa.Text(), nullable=True),
    sa.Column('signature_path', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.ForeignKeyConstraint(['xray_id'], ['xrays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referral_slips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_slips_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_slips_xray_id'), ['xray_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_slips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_slips_xray_id'))
        batch_op.drop_index(batch_op.f('ix_referral_slips_id'))

    op.drop_table('referral_slips')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_xray_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_clinician_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detections_xray_id'))
        batch_op.drop_index(batch_op.f('ix_detections_id'))

    op.drop_table('detections')
    with op.batch_alter_table('xrays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xrays_status'))
        batch_op.drop_index(batch_op.f('ix_xrays_id'))
        batch_op.drop_index(batch_op.f('ix_xrays_claimed_by_id'))
        batch_op.drop_index(batch_op.f('ix_xrays_assigned_to_id'))
        batch_op.drop_index(batch_op.f('ix_xrays_appointment_date'))

    op.drop_table('xrays')
    with op.batch_alter_table('signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signatures_user_id'))
        batch_op.drop_index(batch_op.f('ix_signatures_id'))

    op.drop_table('signatures')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_mrn'))
        batch_op.drop_index(batch_op.f('ix_patients_id'))

    op.drop_table('patients')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_id'))

    op.drop_table('locations')
    # ### end Alembic commands ###
